# Generated by Django 3.2.8 on 2022-07-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
